### ISSUE TITLE
Unable to find the test name for unit tests, in release mode, with test-threads=1

### ISSUE THREAD

**Issue by zazabe** [mitsuhiko/insta#105]
`insta` is not able to find the test name for unit tests, in release mode, with `--test-threads=1` option, even with the "backtrace" feature.

`main.rs`
```rust
#[test]
fn test_snapshot() {
    insta::assert_snapshot!("foo", @"foo");
}
```

`Cargo.toml`
```toml
[...]
[dependencies]
insta = { version = "0.15.0", features = ["backtrace"] }
```

test result:
```
$ cargo test --release --quiet -- --test-threads=1

running 1 test
F
failures:

---- test_snapshot stdout ----
thread 'main' panicked at 'Cannot determine test name from backtrace, no snapshot name can be generated.', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-0.15.0/src/runtime.rs:503:5
[...]
```
