### ISSUE TITLE
Test names are bungled when used with test-env-log crate

### ISSUE THREAD

**Issue by PoignardAzur** [mitsuhiko/insta#154]
Paging @d-e-s-o

## Description

When running a suite of tests annotated with `#[test_env_log::test]` from [the test-env-log crate](https://github.com/d-e-s-o/test-env-log), the snapshots all have the same name, which is `name::of_module::f`, which makes those two crates essentially unusable together.

## Minimal example

I've created a minimal project, with only a `Cargo.toml` and a `src/main.rs` to check the problem still happened there.

```rust
// main.rs
fn main() {
    println!("Hello, world!");
}


use insta::assert_debug_snapshot;

#[test_env_log::test]
fn my_mega_test() {
    assert_debug_snapshot!(42);
}

#[test_env_log::test]
fn some_other_tests() {
    assert_debug_snapshot!(42);
}
```

```toml
# Cargo.toml
[package]
name = "test-insta"
version = "0.1.0"
authors = ["Olivier FAURE <couteaubleu@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.8.2"
insta = "1.5.2"
test-env-log = "0.2.3"
```

**After a run of `cargo test`, I'd expect to see:**

```sh
# ls -1 src/snapshots
test_insta__my_mega_test__f.snap.new
test_insta__some_other_tests__f.snap.new
```

(which would match the test names as reported by cargo test)

**Instead, I get:**

```sh
# ls -1 src/snapshots
test_insta__f-2.snap.new
test_insta__f.snap.new
```

I'm not familiar enough with either codebase to know where the problem might come from, though.
