### ISSUE TITLE
Redactions does not work with btree keys

### ISSUE THREAD

**Issue by danielgatis** [mitsuhiko/insta#192]
## Description

redactions does not works for btree keys.

## Reproduction steps

In test:

```rust
insta::assert_yaml_snapshot!(&book, {
    ".**.timestamp" => "[timestamp]"
});
```

result:

```yaml
market: USD/BTC
bids:
  side: 1
  map: {}
  tree: {}
asks:
  side: 0
  map:
    1:
      id: 1
      trader_id: 1
      price: 500
      qty: 5
      timestamp: "[timestamp]"
      side: 0
  tree:
    ? price: 500
      timestamp: 1629899989141
      side: 0
    : id: 1
      trader_id: 1
      price: 500
      qty: 5
      timestamp: "[timestamp]"
      side: 0
seq: 1
```

Additional helpful information:

- Version of insta: 1.7.2
- Version of rustc: v1.56.0-nightly
- Operating system and version: macOS 11.5.1

## What did you expect

The timestamp in the btree key should be replaced.
