### ISSUE TITLE
Strange behaviour with filters containing escaped backslashes

### ISSUE THREAD

**Issue by Heliozoa** [mitsuhiko/insta#354]
### What happened?

Hi,
thanks for your work on insta.

It looks like maybe the input is escaped before being replaced with the filters, leading to a single backslash getting replaced twice, or something like that?

I hit this issue while trying to figure out why lines in the snapshot test output were quoted on Windows CI. I think it's caused by the same issue (filter `(r"\\\\", "/")` on `r"src\main\java"` results in `"src/main/java"` instead of the expected `src/main/java`, I guess in hindsight needing four backslashes in the filter for it to work was odd already).

### Reproduction steps

With the project
```toml
# Cargo.toml
[package]
name = "issue"
version = "0.1.0"
edition = "2021"

[dependencies]
insta = { version = "1.28.0", features = ["yaml", "filters"] }
```

```rs
// src/lib.rs
#[test]
fn test() {
    insta::with_settings!({filters => vec![
        (r"\\", "replacement"),
    ]}, {
        insta::assert_yaml_snapshot!(vec![
            r"\",
        ]);
    })
}
```
running `cargo insta test` results in
```yaml
---
source: src/lib.rs
expression: "vec![r\"\\\",]"
---
- "replacementreplacement"
```

### Insta Version

1.28.0

### rustc Version

rustc 1.67.1 (d5a82bbd2 2023-02-07)

### What did you expect?

```yaml
---
source: src/lib.rs
expression: "vec![r\"\\\",]"
---
- replacement


```
