### ISSUE TITLE
Instability and Unpredictable Snapshot Order in Tests using Insta and SQLx

### ISSUE THREAD

**Issue by flappyBug** [mitsuhiko/insta#434]
### What happened?

I'm experiencing instability and unpredictable behavior when running tests with Insta and SQLx. Specifically, the order of snapshots seems to be inconsistent, leading to test failures.

### Reproduction steps

Reproducible Code:

```rust
#[cfg(test)]
mod tests {
    use sqlx::{Sqlite, Pool, Row};

    #[sqlx::test]
    fn snapshot1(pool: Pool<Sqlite>) -> sqlx::Result<()> {
        let foo = sqlx::query("SELECT 1 as 'bar'")
            .fetch_one(&pool)
            .await?;

        insta::assert_debug_snapshot!(foo.get::<i32, _>("bar"));

        Ok(())
    }

    #[sqlx::test]
    fn snapshot2(pool: Pool<Sqlite>) -> sqlx::Result<()> {
        let foo = sqlx::query("SELECT 2 as 'bar'")
            .fetch_one(&pool)
            .await?;

        insta::assert_debug_snapshot!(foo.get::<i32, _>("bar"));

        Ok(())
    }
}
```
My dependencies:
```toml
[dependencies]
sqlx = { version = "0.7.3", default-features = false, features = [
    "sqlite",
    "runtime-tokio",
    "macros",
    "migrate",
    "chrono",
    "uuid",
] }
[dev-dependencies]
insta = {version = "1.34.0", features = ["redactions", "filters"]}

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
```

Then run `cargo insta test --review`. Accept once, and run multiple times. Sometimes tests fail due to unexpected snapshot order.

My OS and chip:
`macOS 14.1.1 (23B81), Apple M2 Pro`

### Insta Version

1.34.0

### rustc Version

rustc 1.73.0 (cc66ad468 2023-10-03)

### What did you expect?

I expect the snapshots to maintain a consistent order during test execution, ensuring reliable and stable results.
