### ISSUE TITLE
Find a different syntax for inline snapshot so that cargo fmt can work

### ISSUE THREAD

**Issue by tisonkun** [mitsuhiko/insta#499]
Currently, `@r###"..."###` the inline snapshot syntax is invalid during `cargo fmt` analyze and cannot be formatted.

Perhaps a different syntax (e.g. `i=r""`) can be used for helping in this case.

**Comment by max-sixty** [comment]
Check out https://github.com/mitsuhiko/insta/issues/456, both this:

> Would be great for inline snapshots to work with `rustfmt`, but don't think there's a way — if the inline snapshot is a normal expression without special syntax (such as `@`), it's not possible to discriminate between `(name, value)` and `(value, snapshot)`

...and the broader discussion.

I agree that it would be great to allow rustfmt to work, though lots of other tradeoffs...

**Comment by andylokandy** [comment]
Sharing my workaround:

1. before `cargo fmt`, run `sg scan --rule <path to yaml>` (need install ast-grep)
```yaml
# Replace `@` with `-` in macros
id: pre-format
language: Rust
rule:
  pattern: '@'
  precedes:
    kind: raw_string_literal
  inside:
    kind: macro_invocation
    stopBy: end
fix: '-'
```

2. run `cargo fmt`

3. run `sg scan --rule <path to yaml>`
```yml
# Replace `-` with `@` in macros
id: post-format-0
language: Rust
rule:
  pattern: '-'
  precedes:
    kind: raw_string_literal
  inside:
    kind: macro_invocation
    stopBy: end
fix: '@'
```
